### PR TITLE
Found TZ bug when pulling events

### PR DESCRIPTION
**Pull request by emilyboda**
I was getting a bug where recurring_ical_events was pulling events that were after UTC midnight but before my local timezone midnight. This affected my personal calendars, but also affected the default holiday calendar (although the picture does not show the default holiday calendar). The event in the picture ends at 2200 EDT on June 17th (which is 0200 UTC on June 18th).
Inked20200618_092849_LI

I discovered that the recurring_ical_events conditions must be in UTC, but we were giving them date/times in local time. I converted the t_recurring variables to UTC and then made sure they were formatted correctly for the call.

This error is only obvious for those on a timezone west of UTC.

### CODE REVIEW

**Comment by Ribitsch** [comment]
hey I just wanted to post the same error 
Bildschirmfoto 2020-06-18 um 19 17 25

**Comment by emilyboda** [comment]
@ribitsch What timezone are you in?

**Comment by emilyboda** [comment]
Did you get that error before or after you tried my fix? I only expected people who were on the western side of UTC to get the error, so if you were seeing the same error on the eastern side before my fix I may have misunderstood what was causing it.

**Comment by Ribitsch** [comment]
> @Ribitsch
> 
> Did you get that error before or after you tried my fix? I only expected people who were on the western side of UTC to get the error, so if you were seeing the same error on the eastern side before my fix I may have misunderstood what was causing it.
> 
> Edit: also happy birthday to your father :)

ihm, i did not see, that you have a fix for that available (no I just used the newest version of the dev2 branch)

and thanks :D

**Comment by emilyboda** [comment]
@Ribitsch before you implement the fix, can you test something for me? Add an event on one of your calendars at 2359 to 2359 on June 17th called "before midnight" and an event from 0001 to 0001 on June 18th called "after midnight" and see which show up?

**Comment by aceisace** [comment]
@emilyboda 
Just checked the event before and event after midnight, see the output:
```python3
running ical_parser in standalone mode
Juneteenth    | 19 Jun 20 00:00 | 20 Jun 20 00:00
Father's Day  | 21 Jun 20 00:00 | 22 Jun 20 00:00
23 June bm    | 23 Jun 20 23:50 | 23 Jun 20 23:55
24 am         | 24 Jun 20 00:05 | 24 Jun 20 00:10
```
Timezone = CEST

23 June bm = 23rd June @23.50 until 23.55
24 June am = 24 June @00.05 until @00.10

**Comment by emilyboda** [comment]
@aceisace 
In order for the error to show itself, you need to add the "bm" event to 23.59 yesterday and the "am" event to 00.01 today. The program is supposed to only show events that take place today and forward, but my calendar is showing some events from yesterday. 

Are you experiencing the same error as me in the current version of the BETA?

**Comment by emilyboda** [comment]
@aceisace 

One related thing to consider: the old version would only show future events (so events from this morning would no longer show up in the afternoon) but the BETA shows all events from today. Should we edit the t_recurring_start variable so it starts at now() instead of midnight of today?

**Comment by Ribitsch** [comment]
@emilyboda

I tried adding the two events
Non of show (the event yesterday doesn’t seem to be shown, the event from today 00:01 has already happened and is therefore not shown

**Comment by emilyboda** [comment]
@Ribitsch Oh, are you on the BETA or the current master version? I believe this issue is only present in the BETA, since it requests all the events from the beginning of the day, whereas the current version requests all events from now on.

**Comment by Ribitsch** [comment]
@emilyboda

I am on the current beta (dev_v2 branch)

**Comment by emilyboda** [comment]
Hmmm... I'm not sure my PR is the solution, but i would like to see if other people are experiencing this issue.
If you're experiencing, please comment your timezone and the start and end times (and dates) of the events that are showing up before the first date headers on your agenda. Also, the version that you are using.

**Pull request closed without merging**
