### PR TITLE
Waveshare7.5b hd (v3) support and code refactor

### PR DESCRIPTION
**Pull request by NathanHoekstra**
- Added support for the newest 7.5 inch (HD) waveshare colour e-paper
- Refactored code to (almost) comply with the PEP 8 codestyle
- Removed rundandant checking of booleans.
- Added type hinting to the functions
- Removed checking for correct data type inside functions because it is not needed anymore (type hinting)
- Fixed various bugs

### CODE REVIEW

**Comment by aceisace** [comment]
Wow, thanks @NathanHoekstra . These are a lot of commits!
I'm still a bit busy but I'll try to make some time soon to review the changes.

**Comment by ste1** [comment]
Great work @NathanHoekstra!

@aceisace I would really appreciate a quick implementation as I by mistake bought the HD display and have problems to get the programme started :)

Thank you both for your efforts!

**Comment by aceisace** [comment]
@ste1 I've ordered a new 7.5" v3 ePaper display from waveshare so I can add the support for the v3 model a bit faster. I'm estimating it'll take a week or two until it's fully functional and working as expected. Once more progress is made, I'll post an update here and on Discord.

**Comment by ste1** [comment]
@aceisace do you have any updates? When do you expect an implementation? Kind regards!

**Comment by aceisace** [comment]
@ste1 @NathanHoekstra 
Apologies for the late notice. I've implemented the support of the 7.5" v3 ePaper displays in the /dev_ver2_0 branch. At a later date (when all to-do's of the BETA branch are checked and tested), it will be pushed as a new official release.

You can join the Discord server for faster updates on the BETA branch as well as additional help from other developers and contributors.

**Pull request closed without merging**
