### PR TITLE
Added a call to the ICanHazDadJoke API to grab something pleasant.

### PR DESCRIPTION
**Pull request by efredericks**
Module that requests a random dadjoke from the https://icanhazdadjoke.com API.

### CODE REVIEW

**Comment by Atrejoe** [comment]
Ouch, these jokes are bad :)

**Comment by efredericks** [comment]
> Ouch, these jokes are bad :)

If they seem to be bad, then they are functioning as intended :)

**Comment by vitasam** [comment]
Nice job! :) 
One comment for @efredericks  - would you also update `settings.py` with a comment in bottom section how to enable you module? 

`bottom_section = "inkycal_rss"        # "inkycal_rss" # .... `

**Comment by efredericks** [comment]
Done and done.  Updated the contributors file with a section for modules as well in anticipation of others joining on.

**Comment by aceisace** [comment]
@efredericks Hi, thanks for your PR and for developing a custom module for the Inky-Calendar software. Please note that the master branch is reaching EOL so any changes commited to /master now will be lost in the upcoming release.

I'm leaving this PR open so I can adjust the code of your module to support the new release.  I've also updated the contributors file with your name in the /dev_ver2_0 branch.

**Comment by aceisace** [comment]
@efredericks I've started working on the integration of your module in the next release. Apolgies it took so long.
I've added your name in the contributor file and will link the commit for this PR when it's ready.
This also means that I unfortunately cannot merge this PR in favor of the new release. But thank you very much for your hard work and effort to make a third-party module.
I'll be sure to give proper credit in the correspoding module for the next release. Thank you for your understanding.

**Comment by efredericks** [comment]
No worries, thanks for keeping me posted!

On Nov 12, 2020 3:58 PM, Ace <notifications@github.com> wrote:

@efredericks<https://github.com/efredericks> I've started working on the integration of your module in the next release. Apolgies it took so long.
I've added your name in the contributor file and will link the commit for this PR when it's ready.
This also means that I unfortunately cannot merge this PR in favor of the new release. But thank you very much for your hard work and effort to make a third-party module.
I'll be sure to give proper credit in the correspoding module for the next release. Thank you for your understanding.

**Comment by aceisace** [comment]
OK, done! Your module is now fully supported in the next release. Here is the commit for this module:
[icanhazdadapi module](https://github.com/aceisace/Inky-Calendar/commit/8db419fa3713a113a21dccaf4f42f07500785635)

**Pull request closed without merging**
