### PR TITLE
New settings for calendar events

### PR DESCRIPTION
**Pull request by vitasam**
A new settings:
`show_event_begin_only = "false"       # "true" # "false"`

When set to `true` then the only begin date of events are highlighted in Calendar.

### CODE REVIEW

**Comment by vitasam** [comment]
I removed timezones from start and end of the month, within the same PR, now my calendar works as expected.

**Comment by aceisace** [comment]
@vitasam 
Just a quick question; you mentioned that not setting the timezone fixed the problem. Can you elaborate a bit on that? Thanks in advance

**Comment by vitasam** [comment]
> 
> 
> @vitasam
> Just a quick question; you mentioned that not setting the timezone fixed the problem. Can you elaborate a bit on that? Thanks in advance

I was not able to reproduce it now with my current calendar. Let's remove this time-zone from the patch

**Comment by vitasam** [comment]
Now the PR is about new settings only. If I notice timezone problem again with my calendar, I will create a new issue.

**Pull request closed without merging**
